# Generated by Django 5.2.8 on 2025-11-21 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_perfil_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('producto_nombre', models.CharField(max_length=255)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_descuento', models.IntegerField(default=0)),
                ('producto_imagen', models.URLField()),
                ('producto_categoria', models.CharField(max_length=100)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('user', 'producto_id', 'producto_categoria')},
            },
        ),
    ]
