# Generated by Django 5.2.8 on 2025-11-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('yape', 'Yape'), ('plin', 'Plin'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Pago Contra Entrega')], default='efectivo', max_length=20),
        ),
    ]
