# Generated by Django 5.2.8 on 2025-11-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedido_estado_pago_pedido_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(help_text='ID del producto en la API externa', unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.IntegerField(default=0, help_text='Porcentaje de descuento')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('stock_minimo', models.IntegerField(default=5, help_text='Alerta cuando el stock sea menor a este valor')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Desactivar producto sin eliminarlo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Pago Contra Entrega')], default='efectivo', max_length=20),
        ),
    ]
