"""
Django settings for superventas project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Inicializar environ
env = environ.Env(
    DEBUG=(bool, True)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Leer archivo .env si existe
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rd+4yr)@w*-az5^o@s(j@_8ja#3k07a5$vny+h&!5cwlsmh^5e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'andres-bioclimatic-sarina.ngrok-free.dev']

# CSRF Configuration
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SECURE = False  # True solo en producción con HTTPS
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000', 'https://andres-bioclimatic-sarina.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Debe ir ANTES de django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ventas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'superventas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'superventas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Montevideo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (archivos subidos por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración Twilio WhatsApp (opcional - solo si usas WhatsApp Bot)
try:
    TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
    TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
    TWILIO_WHATSAPP_NUMBER = env('TWILIO_WHATSAPP_NUMBER', default='')
except:
    TWILIO_ACCOUNT_SID = ''
    TWILIO_AUTH_TOKEN = ''
    TWILIO_WHATSAPP_NUMBER = ''

# Configuración Mercado Pago
# Para obtener tus credenciales, ve a: https://www.mercadopago.com.uy/developers/panel
try:
    MERCADOPAGO_ACCESS_TOKEN = env('MERCADOPAGO_ACCESS_TOKEN', default='')
    MERCADOPAGO_PUBLIC_KEY = env('MERCADOPAGO_PUBLIC_KEY', default='')
except:
    MERCADOPAGO_ACCESS_TOKEN = ''
    MERCADOPAGO_PUBLIC_KEY = ''

# Configuración Stripe
# Para obtener tus credenciales, ve a: https://dashboard.stripe.com/test/apikeys
try:
    STRIPE_PUBLIC_KEY = env('STRIPE_PUBLIC_KEY', default='')
    STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
except:
    STRIPE_PUBLIC_KEY = ''
    STRIPE_SECRET_KEY = ''

# Configuración Groq (Chatbot con IA - Gratis)
# Para obtener tu API Key gratis, ve a: https://console.groq.com/
try:
    GROQ_API_KEY = env('GROQ_API_KEY', default='')
except:
    GROQ_API_KEY = ''

# Configuración de Email
# Para Gmail: https://myaccount.google.com/apppasswords (necesitas contraseña de aplicación)
# Modo desarrollo: los emails se muestran en consola
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Modo producción: descomentar las siguientes líneas y comentar la línea de arriba
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
# EMAIL_PORT = env.int('EMAIL_PORT', default=587)
# EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
# EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Email para recibir notificaciones de pedidos
ADMIN_EMAIL = env('ADMIN_EMAIL', default='')

# ============================================
# CONFIGURACIÓN DE JAZZMIN (ADMIN MODERNO)
# ============================================

JAZZMIN_SETTINGS = {
    # Título en la barra superior
    "site_title": "Superventas Admin",
    
    # Título en la página de login
    "site_header": "Superventas",
    
    # Marca en la barra superior
    "site_brand": "Superventas",
    
    # Logo para usar en el login y barra superior (opcional)
    # "site_logo": "images/logo.png",
    
    # Logo para el modo oscuro (opcional)
    # "site_logo_dark": "images/logo-dark.png",
    
    # Bienvenida en la página de inicio
    "welcome_sign": "Bienvenido al Panel de Administración de Superventas",
    
    # Copyright en el footer
    "copyright": "Superventas © 2025",
    
    # Links en el menú superior derecho
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Tienda", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],
    
    # Orden del menú lateral
    "order_with_respect_to": ["ventas", "auth"],
    
    # Iconos personalizados para cada app y modelo
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "ventas.Pedido": "fas fa-shopping-cart",
        "ventas.DetallePedido": "fas fa-list",
        "ventas.Perfil": "fas fa-id-card",
        "ventas.Favorito": "fas fa-heart",
    },
    
    # Iconos por defecto
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Temas de color disponibles
    "theme": "cosmo",  # opciones: cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, slate, solar, spacelab, superhero, united, yeti
    
    # Modo oscuro
    "dark_mode_theme": None,
    
    # Botón para cambiar tema
    "show_ui_builder": False,
    
    # Cambiar entre modo claro/oscuro
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
    # Sidebar personalizado
    "navigation_expanded": True,
    
    # Ocultar apps
    "hide_apps": [],
    
    # Ocultar modelos
    "hide_models": [],
    
    # Ordenar apps (personalizado)
    "custom_links": {
        "ventas": [{
            "name": "Ver Pedidos Pendientes",
            "url": "/admin/ventas/pedido/?estado__exact=pendiente",
            "icon": "fas fa-clock",
            "permissions": ["ventas.view_pedido"]
        }]
    },
    
    # Usar botones redondeados
    "use_google_fonts_cdn": True,
    "show_sidebar": True,
    "language_chooser": False,
}

# Configuración adicional de la UI de Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-secondary",
        "secondary": "btn-secondary",
        "info": "btn-secondary",
        "warning": "btn-secondary",
        "danger": "btn-secondary",
        "success": "btn-secondary"
    }
}
